export default resultados = [
    {
        id: '01',
        cliente: 'Ana',
        aparelho: 'MTB',
        descricaoBike: 'Bike vermelha com desenho',
        contato: '09999999999',
        data: '12/09/2023',
        hora: '09:30 AM', // Hora fictícia
        local: 'Remigio',
        tipoM: 'revisão',
        pagamento: '50',
        endereco: 'Rua da Ana, 123, Remigio, PB',
    },
    {
        id: '02',
        cliente: 'Ana',
        aparelho: 'MTB',
        descricaoBike: 'Bike vermelha com desenho',
        contato: '83 99999-9999',
        data: '12/09/2023',
        hora: '10:00 AM', // Hora fictícia
        local: 'Remigio',
        tipoM: 'revisão',
        pagamento: '45',
        endereco: 'Rua da Ana, 123, Remigio, PB',
    },
    {
        id: '03',
        cliente: 'Maria',
        aparelho: 'Speed',
        descricaoBike: 'Bike amarela com adesivos',
        contato: '07777777777',
        data: '12/09/2023',
        hora: '11:15 AM', // Hora fictícia
        local: 'Remigio',
        tipoM: 'revisão',
        pagamento: '60',
        endereco: 'Rua da Maria, 456, Remigio, PB',
    },
    {
        id: '04',
        cliente: 'João',
        aparelho: 'MTB',
        descricaoBike: 'Bike preta simples',
        contato: '08888888888',
        data: '15/09/2023',
        hora: '02:45 PM', // Hora fictícia
        local: 'Campina Grande',
        tipoM: 'manutenção',
        pagamento: '75',
        endereco: 'Avenida do João, 789, Campina Grande, PB',
    },
    {
        id: '05',
        cliente: 'Maria',
        aparelho: 'Speed',
        descricaoBike: 'Bike branca com adesivos',
        contato: '07777777777',
        data: '18/09/2023',
        hora: '03:30 PM', // Hora fictícia
        local: 'João Pessoa',
        tipoM: 'reparo',
        pagamento: '90',
        endereco: 'Rua da Maria, 123, João Pessoa, PB',
    },
    {
        id: '06',
        cliente: 'Pedro',
        aparelho: 'Speed',
        descricaoBike: 'Bike azul com faixas',
        contato: '06666666666',
        data: '20/09/2023',
        hora: '10:30 AM', // Hora fictícia
        local: 'São Paulo',
        tipoM: 'instalação',
        pagamento: '70',
        endereco: 'Rua do Pedro, 789, São Paulo, SP',
    },
    {
        id: '07',
        cliente: 'Laura',
        aparelho: 'Speed',
        descricaoBike: 'Bike rosa com decoração',
        contato: '05555555555',
        data: '25/09/2023',
        hora: '11:00 AM', // Hora fictícia
        local: 'Rio de Janeiro',
        tipoM: 'limpeza',
        pagamento: '80',
        endereco: 'Avenida da Laura, 456, Rio de Janeiro, RJ',
    },
]
